import { Octokit } from '@octokit/rest'
import type { VulnMatch } from '../types.js'

interface RepoInfo {
  owner: string
  repo: string
}

function parseGitHubUrl(url: string): RepoInfo | null {
  const match = url.match(/github\.com[:/]([^/]+)\/([^/.]+)(?:\.git)?/)
  if (!match) return null
  return { owner: match[1], repo: match[2] }
}

export async function getOctokit(): Promise<Octokit> {
  const token = process.env.GITHUB_TOKEN
  if (!token) {
    throw new Error(
      'GITHUB_TOKEN environment variable is not set.\n' +
      'Create a token at https://github.com/settings/tokens with:\n' +
      '  - contents: write\n' +
      '  - pull-requests: write'
    )
  }
  return new Octokit({ auth: token })
}

export async function checkTokenPermissions(octokit: Octokit, owner: string, repo: string): Promise<void> {
  try {
    const { data } = await octokit.rest.repos.get({ owner, repo })
    const perms = (data as { permissions?: Record<string, boolean> }).permissions
    if (perms && !perms.push) {
      throw new Error(
        `GitHub token lacks write access to ${owner}/${repo}.\n` +
        'Ensure your token has: contents: write, pull-requests: write'
      )
    }
  } catch (err: unknown) {
    if (err instanceof Error && err.message.includes('lacks write access')) throw err
    if (err instanceof Error && (err as { status?: number }).status === 404) {
      throw new Error(`Repository ${owner}/${repo} not found or token lacks read access.`)
    }
    throw err
  }
}

/** Create one PR for a group of vulns affecting the same package */
export async function createFixPr(
  octokit: Octokit,
  repoUrl: string,
  vulns: VulnMatch[],         // all vulns for one package
  fixVersion: string,         // highest safe version to bump to
  packageJsonContent: string
): Promise<string> {
  const info = parseGitHubUrl(repoUrl)
  if (!info) throw new Error(`Cannot parse GitHub URL: ${repoUrl}`)
  const { owner, repo } = info

  const pkgName = vulns[0].package
  const installedVersion = vulns[0].installedVersion

  // Get default branch SHA
  const { data: repoData } = await octokit.rest.repos.get({ owner, repo })
  const defaultBranch = repoData.default_branch
  const { data: refData } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  })
  const baseSha = refData.object.sha

  // Branch name: fix/pkg-name (no CVE ID — covers all CVEs for this package)
  const branchName = `nodeguard/fix-${pkgName.replace(/[@/]/g, '-')}`
  try {
    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    })
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 422) {
      throw new Error(`Branch ${branchName} already exists. PR may have been created already.`)
    }
    throw err
  }

  // Get current package.json blob SHA
  const { data: fileData } = await octokit.rest.repos.getContent({
    owner,
    repo,
    path: 'package.json',
    ref: defaultBranch,
  })

  if (Array.isArray(fileData) || fileData.type !== 'file') {
    throw new Error('package.json not found or is a directory')
  }

  // Commit bumped package.json
  const ids = vulns.map(v => v.id).join(', ')
  const encodedContent = Buffer.from(packageJsonContent).toString('base64')
  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: 'package.json',
    message: `fix(deps): bump ${pkgName} to ${fixVersion}\n\nFixes: ${ids}`,
    content: encodedContent,
    sha: fileData.sha,
    branch: branchName,
  })

  // Build PR body listing all CVEs fixed
  const vulnRows = vulns
    .map(v => `| ${v.id} | ${v.severity} | ${v.summary} |`)
    .join('\n')

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `fix(deps): bump ${pkgName} from ${installedVersion} to ${fixVersion}`,
    body: [
      `## Security Fix\n`,
      `Bumps \`${pkgName}\` from \`${installedVersion}\` to \`${fixVersion}\` to address ${vulns.length} vulnerabilit${vulns.length === 1 ? 'y' : 'ies'}.\n`,
      `| ID | Severity | Summary |`,
      `|----|----------|---------|`,
      vulnRows,
      `\n---\n_Generated by [NodeGuard](https://github.com/nodeguard/nodeguard)_`,
    ].join('\n'),
    head: branchName,
    base: defaultBranch,
  })

  return pr.html_url
}

/** Bump a version in a package.json string */
export function bumpPackageJson(content: string, packageName: string, newVersion: string): string {
  const manifest = JSON.parse(content)
  for (const field of ['dependencies', 'devDependencies', 'optionalDependencies', 'peerDependencies']) {
    if (manifest[field]?.[packageName] !== undefined) {
      // Preserve range prefix (^, ~, etc.) if present
      const current: string = manifest[field][packageName]
      const prefix = /^[\^~>=<]/.test(current) ? current.match(/^[^0-9]*/)?.[0] ?? '' : ''
      manifest[field][packageName] = `${prefix}${newVersion}`
    }
  }
  return JSON.stringify(manifest, null, 2) + '\n'
}
