apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodeguard.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodeguard.labels" . | nindent 4 }}
type: Opaque
data:
  githubToken: {{ .Values.secret.githubToken | b64enc | quote }}
